version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "leaderboard"
      POSTGRES_USER: "mykyta"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5454:5454"